version: "3.7"

services:
  mysql:
    container_name: mysql_db
    build:
      context: .
      dockerfile: ./database/docker/db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "courses"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
    ports:
      - 3306:3306
    volumes:
      - ./database/data/:/var/lib/mysql/
    restart: always
